const GET_USER = 'GET_USER'
const GET_USER_TODOS = 'GET_USER_TODOS'
const ADD_USER_TODOS = 'ADD_USER_TODOS'
const LOGOUT = 'LOGOUT'
const UPDATE_TODO = 'UPDATE_TODO'
const REMOVE_TODO = 'REMOVE_TODO'
const ERROR_TODOS = 'ERROR_TODOS'
const USER_ERROR = 'USER_ERROR'

module.exports = {
    GET_USER,
    GET_USER_TODOS,
    ADD_USER_TODOS,
    UPDATE_TODO,
    REMOVE_TODO,
    ERROR_TODOS,
    LOGOUT,
    USER_ERROR
}